---
  - name: "Remove user {{ item.name }}"
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      state: "{{ item.state }}"
      remove: "{{ item.remove | default('no') }}"

  - name: "Remove group {{ item.group_name | default(item.name) }}"
    group:
      name: "{{ item.group_name | default(item.name) }}"
      gid: "{{ item.gid | default(item.uid) }}"
      state: "{{ item.state }}"
