---
  - name: Include OS-Specific variables/overrides
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"

  - name: Set resolv.conf configuration
    template:
      dest: /etc/resolv.conf
      src: resolv_conf.j2
      owner: 0
      group: 0
      mode: 0644

