---
  - name: Include OS-Specific variables/overrides
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "main.yml"

  - name: Set Foo 
    template:
      dest: /tmp/foo
      src: "{{ role_path }}/templates/foo.j2"
      owner: 0
      group: 0
      mode: 0644

